# Generated by Django 6.0.3 on 2026-04-03 15:41

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lottery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), help_text='主號碼 (已排序)')),
                ('special_number', models.IntegerField(blank=True, null=True)),
                ('strategy', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_term', models.CharField(blank=True, max_length=20, null=True)),
                ('matched_count', models.IntegerField(blank=True, null=True)),
                ('special_matched', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.lotterygame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '收藏預測',
                'verbose_name_plural': '收藏預測',
                'db_table': 'saved_predictions',
                'ordering': ['-created_at'],
            },
        ),
    ]
