# Generated by Django 4.2.16 on 2026-04-03 09:29

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='遊戲代碼，如 daily_cash, lotto649, super_lotto', max_length=20, unique=True)),
                ('name', models.CharField(help_text='遊戲名稱，如 今彩539', max_length=50)),
                ('main_pool_size', models.SmallIntegerField(help_text='主區可選號碼上限')),
                ('main_pick_count', models.SmallIntegerField(help_text='主區開出幾球')),
                ('has_special', models.BooleanField(default=False, help_text='是否有特別號')),
                ('special_pool_size', models.SmallIntegerField(blank=True, help_text='特別號池大小 (大樂透=49, 威力彩=8)', null=True)),
                ('draw_schedule', models.CharField(blank=True, default='', help_text='開獎日描述，如 Mon,Thu', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '彩券遊戲',
                'verbose_name_plural': '彩券遊戲',
                'db_table': 'lottery_games',
            },
        ),
        migrations.CreateModel(
            name='DrawResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_term', models.CharField(help_text='期數，如 113000001', max_length=20)),
                ('draw_date', models.DateField(help_text='開獎日期')),
                ('numbers_ordered', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), help_text='依落球順序 (原始開出順序)', size=None)),
                ('numbers_sorted', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), help_text='依大小排序 (方便統計查詢)', size=None)),
                ('special_number', models.IntegerField(blank=True, help_text='特別號 (大樂透/威力彩第二區)', null=True)),
                ('total_sales', models.BigIntegerField(blank=True, help_text='該期銷售額', null=True)),
                ('raw_data', models.JSONField(blank=True, help_text='原始爬蟲回傳資料 (備查)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(help_text='所屬彩券遊戲', on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='lottery.lotterygame')),
            ],
            options={
                'verbose_name': '開獎紀錄',
                'verbose_name_plural': '開獎紀錄',
                'db_table': 'draw_results',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['numbers_sorted'], name='idx_numbers_sorted_gin'), django.contrib.postgres.indexes.GinIndex(fields=['numbers_ordered'], name='idx_numbers_ordered_gin'), models.Index(fields=['game', '-draw_date'], name='idx_game_date'), models.Index(fields=['game', 'draw_term'], name='idx_game_term')],
            },
        ),
        migrations.AddConstraint(
            model_name='drawresult',
            constraint=models.UniqueConstraint(fields=('game', 'draw_term'), name='uq_game_term'),
        ),
    ]
